# SPDX-FileCopyrightText: 2025 Stackable GmbH
# SPDX-License-Identifier: Apache-2.0
---
name: Release nifi-migrate

on:
  push:
    tags:
      - "rel/nifi-migrate-[0-9]+.[0-9]+.[0-9]+**"

env:
  RUST_VERSION: 1.87.0

permissions: {}

jobs:
  create-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to create the draft release
    steps:
      - name: Create Draft Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          draft: true

  build:
    name: Build nifi-migrate
    needs:
      - create-release
    permissions:
      contents: write # required to upload release assets
    strategy:
      fail-fast: false
      matrix:
        targets:
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-24.04-arm }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: aarch64-apple-darwin, os: macos-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
    runs-on: ${{ matrix.targets.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.targets.target }}

      - name: Build Binary
        run: cargo build --target ${{ matrix.targets.target }} --release --package nifi-migrate

      - name: Rename Binary (Unix)
        if: runner.os != 'Windows'
        run: mv target/${{ matrix.targets.target }}/release/nifi-migrate nifi-migrate-${{ matrix.targets.target }}

      - name: Rename Binary (Windows)
        if: runner.os == 'Windows'
        run: mv target/${{ matrix.targets.target }}/release/nifi-migrate.exe nifi-migrate-${{ matrix.targets.target }}.exe

      - name: Upload Artifact to Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          draft: true
          files: nifi-migrate-${{ matrix.targets.target }}${{ runner.os == 'Windows' && '.exe' || '' }}

  publish-release:
    name: Publish Release
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to publish the release
    steps:
      - name: Publish Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          draft: false
