# SPDX-FileCopyrightText: 2025 Stackable GmbH
# SPDX-License-Identifier: Apache-2.0
---
name: pre-commit

on:
  pull_request:

env:
  RUST_TOOLCHAIN_VERSION: "1.87.0"

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: stackabletech/actions/run-pre-commit@0fe048f952bee522474903a925ea48dc706a0bb4 # v0.17.5
        with:
          rust: ${{ env.RUST_TOOLCHAIN_VERSION }}
