# SPDX-FileCopyrightText: 2025 Stackable GmbH
# SPDX-License-Identifier: Apache-2.0

name: pre-commit

on:
  pull_request:

env:
  RUST_TOOLCHAIN_VERSION: "1.87.0"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: stackabletech/actions/run-pre-commit@a5d39a4eb109bb6af3c152800701c86e98bfe1a5 # v0.10.1
        with:
          rust: ${{ env.RUST_TOOLCHAIN_VERSION }}
